# Generated by Django 3.0.3 on 2020-02-25 11:38

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='이메일(아이디)', max_length=64, unique=True, verbose_name='email id')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_delete', models.DateTimeField(blank=True, default=None, help_text='계정 삭제 여부', null=True)),
                ('type', models.CharField(blank=True, choices=[('g', '일반 계정'), ('b', '비니지스 계정'), ('a', '관리자')], max_length=1, null=True, verbose_name='user type')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='이름', max_length=20, null=True, verbose_name='name')),
                ('gender', models.CharField(blank=True, help_text='성별', max_length=6, null=True, verbose_name='gender')),
                ('personal_presentation', models.TextField(blank=True, help_text='자기 소개', null=True, verbose_name='personal presentation')),
                ('location', models.TextField(blank=True, help_text='위치', null=True, verbose_name='location')),
                ('web_site', models.URLField(blank=True, help_text='웹사이트', null=True, verbose_name='web site')),
                ('country_code', models.TextField(blank=True, help_text='국가 코드', max_length=2, null=True, verbose_name='contry code')),
                ('is_adult', models.BooleanField(default=False, help_text='성인 여부', verbose_name='adult certification')),
                ('user', models.OneToOneField(blank=True, help_text='연결된 계정', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
