# Generated by Django 3.0.3 on 2020-02-25 11:38

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Board의 이름입니다.', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='보드의 설명입니다.', max_length=500, null=True)),
                ('subject', models.CharField(blank=True, help_text='보드의 주제입니다.', max_length=100, null=True)),
                ('is_inspired', models.BooleanField(default=False, help_text='보드의 영감 공개 여부입니다..')),
                ('is_save', models.BooleanField(default=False, help_text='보드의 저장여부입니다.')),
                ('is_private', models.BooleanField(default=False, help_text='보드의 공개여부입니다.')),
                ('order_key', models.IntegerField(blank=True, help_text='보드의 사용자 정렬입니다.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('related_link', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, help_text='크리덴셜과 연결된 주요 프로필 사진입니다.', max_length=200, storage=django.core.files.storage.FileSystemStorage(), upload_to='pins/%Y/%m/%d', verbose_name='photo (주요 프로필 사진)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='섹션의 이름입니다.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_id', to='boards.Board')),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_id', to='boards.Pin')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='section',
            field=models.ManyToManyField(blank=True, help_text='보드의 섹션입니다.', null=True, related_name='section', through='boards.Section', to='boards.Pin'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ManyToManyField(help_text='보드의 참여자입니다.', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
